TRANSITIONS = {
    "INIT": ["REQUIREMENT_DISCUSSION"],
    "REQUIREMENT_DISCUSSION": ["REQUIREMENT_REVIEW"],
    "REQUIREMENT_REVIEW": ["REQUIREMENT_APPROVED", "REQUIREMENT_REVISION"],
    "REQUIREMENT_REVISION": ["REQUIREMENT_DISCUSSION"],
    "REQUIREMENT_APPROVED": ["DESIGN_AND_TESTCASE_DRAFTING"],
    "DESIGN_AND_TESTCASE_DRAFTING": ["DESIGN_REVIEW"],
    "DESIGN_REVIEW": ["DEVELOPMENT", "DESIGN_TESTCASE_REVISION"],
    "DESIGN_TESTCASE_REVISION": ["DESIGN_AND_TESTCASE_DRAFTING"],
    "DEVELOPMENT": ["TEST_AND_SECURITY_VALIDATION"],
    "TEST_AND_SECURITY_VALIDATION": ["PRODUCT_ACCEPTANCE", "DEVELOPMENT"],
    "PRODUCT_ACCEPTANCE": ["DONE", "DEVELOPMENT"],
    "DONE": [],
}


def allowed_transitions(current_phase: str) -> list[str]:
    return TRANSITIONS.get(current_phase, [])


def can_transition(from_phase: str, to_phase: str) -> bool:
    return to_phase in allowed_transitions(from_phase)
